name: liteproxy.ui

networks:
  kong:
    driver: bridge
    name: kong-net

services:
  liteproxy-ui:
    container_name: liteproxy-ui-service
    build:
      context: ./
    networks:
      - kong
    ports:
      - 3001:3001

    restart: always
    labels:
      - 'liteproxy'
      - 'vite'
